### ISSUE TITLE
Add an option to truncate extremely long track names or split them up in 2 lines 

### ISSUE THREAD

**Issue by CatzHoekk** [Phlarx/tm-ultimate-medals#30]
Todays TOTD "Backwards Progression ft AgentWhiskey & Henkisme" has such an extremly long name that the HUD takes up a third of the width of my screen. I am exaggerating but its immense. 

![image](https://user-images.githubusercontent.com/69237200/201410824-e30c2b68-a18b-4bef-b7a5-63a7fb9c6636.png)

I would be cool if that could be adjusted somehow.  

Maps containing "ft" or "ft." could be split in 2 lines, maybe even with a lower fontsize for the 2nd line or something

**Comment by Phlarx** [comment]
Also to consider: the effect of newlines within the actual map name.
